Footer
vtyshchenko/project-filmoteka pull request #10
Opened 2021-11-08 20:08 UTC by dimperesichan

2021-11-08 20:52 UTC, vtyshchenko requested changes

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +.footer-cont__txt1,
видали всі 3 класи і залиш лише один

2021-11-08 20:52 UTC, vtyshchenko commented on src/partials/footer.html
> +            <p class="footer-cont__txt1"> @ 2019|All rights reserved|</p>
footer-cont__txt1 заміни на footer-cont__txt

2021-11-08 20:52 UTC, vtyshchenko commented on src/partials/footer.html
> +            <p class="footer-cont__txt2"> Developed with </p>
footer-cont__txt2 заміни на footer-cont__txt

2021-11-08 20:52 UTC, vtyshchenko commented on src/partials/footer.html
> +            <p class="footer-cont__txt3"> by GoIT Students</p>
footer-cont__txt3 заміни на footer-cont__txt

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +    font-family: Roboto;
в _variables.scss є змінна для шрифта

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +    font-weight: normal;
font-style: normal;
    font-weight: normal;

вони по замовчуванню такі - видали

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +    color: #545454;
для кольорів є в _variables.scss є змінні - використай їх

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +    background-color: #545454;
для кольорів є в _variables.scss є змінні - використай їх

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +.footer-cont__txt1,
такі класи вже є зверху

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +.footer-cont__txt3{
дубляж класу - розберись

2021-11-08 20:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
> +.footer-cont__txt3{
знову дубляж - пооб'єднуй їх в одне

2021-11-08 20:59 UTC, emmavasylyk requested changes

2021-11-08 20:59 UTC, emmavasylyk commented on src/partials/footer.html
> +            <p class="footer-cont__txt1"> @ 2019|All rights reserved|</p>
@ ставиться мневмокодом.

2021-11-08 20:59 UTC, emmavasylyk commented on src/partials/footer.html
> +            <p class="footer-cont__txt3"> by GoIT Students</p>
GoIT Students это  ссылка по которой будет открываться модальное окно и инфой про разработчиков

2021-11-08 20:59 UTC, emmavasylyk commented on src/sass/layout/_footer.scss
> +    background: #F7F7F7;
цвет проставляется переменной из файле _variables.scss исправь по всему файлу.

2021-11-08 20:59 UTC, emmavasylyk commented on src/sass/layout/_footer.scss
> +    font-family: Roboto;
ПРОСМОТРИ ВЕСЬ ФАЙЛ СТИЛЕЙ! и по удаляй повторы в коде
1) font-style: normal - убирай, значение normal не проставляется
2)  font-weight: normal; - пишеться цыфрами normal - указан по умолчанию уже.
3) position: static; - не проставляеться если значение  static - указан по умолчанию уже.
4)  line-height: 19px; правильно проставлять без пикселей это надо line-height разделить font-size = 1.19

2021-11-10 08:10 UTC, vtyshchenko requested changes
всі невідповідні медіаправила переписати
повинні всі бути такими (иедіаправила всередині класу, а не класи всередині медіаправила):
.icon-heart{
    @include settings__icons($main-orange-color, 18px, 18px);
        margin-left: 10px;
        margin-right: 10px;
}

а не такими:
@media screen and (max-width: $mobile-min) {
.footer{
    height: 100px;
}

.footer-cont{
    flex-wrap: wrap;
}

.footer-cont__txt
{
    font-size: 13px;
    line-height: 1.23;
}

.footer-container__text{
    padding-bottom: 10px;
}
        
.after{
    &::after{
        width: 97px;
        margin-left: 20px;
    }
}
}

2021-11-10 08:10 UTC, vtyshchenko commented on src/partials/footer.html
> +            <a class="footer-cont__txt link after"href=""> by GoIT Students</a>
href="" не повинен бути пустим - постав href="#"

2021-11-10 21:52 UTC, vtyshchenko requested changes

2021-11-10 21:52 UTC, vtyshchenko commented on src/sass/layout/_footer.scss
>  .after{
такийклас вже є - це дублікат.
Зведи всі класи в один, щоб не повторювалися назви. Напр:
.after{
    position: static;

    &::after{
    position: absolute;
    display: block;
    content: "";
    width: 117px;
    height: 1px;
    background-color: $secondary-text-color; 
    border-radius: 2px;
    margin-left: 25px;
    }
}


.after{
    @media screen and (min-width: $mobile-min) {
    &::after{
        width: 97px;
        margin-left: 20px;
    }
}
}

зроби так:
.after{
    position: static;

    &::after{
    position: absolute;
    display: block;
    content: "";
    width: 117px;
    height: 1px;
    background-color: $secondary-text-color; 
    border-radius: 2px;
    margin-left: 25px;
    }

    @media screen and (min-width: $mobile-min) {
    &::after{
        width: 97px;
        margin-left: 20px;
    }
}
}

2021-11-12 10:00 UTC, vtyshchenko approved these changes

2021-11-12 11:15 UTC, emmavasylyk approved these changes

2021-11-12 11:15 UTC, merged