Feature/team modal
vtyshchenko/project-filmoteka pull request #12
Opened 2021-11-08 22:37 UTC by Vitaliy-Karpenko529

2021-11-09 10:33 UTC, ViktoriiaPavlenko commented on src/partials/about-modal.html
> +                    <source media="(mmi-width: 1024px)"srcset="./images/team/vitaliy-s-desctop.jpg 1x, ./images/team/vitaliy-s-desctop@1.5x.jpg 1.5x, ./images/team/vitaliy-s-desctop@2x.jpg 2x">
mmi-width непраильно написано

2021-11-09 10:35 UTC, ViktoriiaPavlenko requested changes

2021-11-09 10:35 UTC, ViktoriiaPavlenko commented on src/partials/about-modal.html
> +                    <source media="(mmi-width: 1024px)"srcset="./images/team/vitaliy-k-desctop.jpg 1x, ./images/team/vitaliy-k-desctop@1.5x.jpg 1.5x, ./images/team/vitaliy-k-desctop@2x.jpg 2x">
mmi-width неправильно написано, перевір нижче по коду, там такі ж помилки

2021-11-09 16:50 UTC, vtyshchenko requested changes

2021-11-09 16:50 UTC, vtyshchenko commented on src/partials/about-modal.html
> +    <svg class="team__modal-icon" width="30" height="30" viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg">
використай svg

2021-11-09 16:50 UTC, vtyshchenko commented on src/partials/about-modal.html
> +                    <source media="(mmi-width: 1024px)"srcset="./images/team/vitaliy-s-desctop.jpg 1x, ./images/team/vitaliy-s-desctop@1.5x.jpg 1.5x, ./images/team/vitaliy-s-desctop@2x.jpg 2x">
desKtop

2021-11-09 16:50 UTC, vtyshchenko commented on src/sass/components/_about.scss
> +@media screen and (min-width: $tablet) {
медіаправила повинні бути в середині класу

2021-11-09 16:50 UTC, vtyshchenko commented on src/sass/components/_about.scss
> +.container {
такий клас вже є - назви по іншому

2021-11-10 08:33 UTC, vtyshchenko requested changes

2021-11-10 08:33 UTC, vtyshchenko commented on src/js/about.js
> +import refs from "./common/refs";
або це не потрібно  або перенести в рефи те, що написано нижче (другий варіант краще)

2021-11-10 08:57 UTC, Vitaliy-Karpenko529 commented on src/partials/about-modal.html
> +                    <source media="(mmi-width: 1024px)"srcset="./images/team/vitaliy-s-desctop.jpg 1x, ./images/team/vitaliy-s-desctop@1.5x.jpg 1.5x, ./images/team/vitaliy-s-desctop@2x.jpg 2x">
done

2021-11-10 08:57 UTC, Vitaliy-Karpenko529 commented on src/partials/about-modal.html
> +                    <source media="(mmi-width: 1024px)"srcset="./images/team/vitaliy-k-desctop.jpg 1x, ./images/team/vitaliy-k-desctop@1.5x.jpg 1.5x, ./images/team/vitaliy-k-desctop@2x.jpg 2x">
done

2021-11-10 08:58 UTC, Vitaliy-Karpenko529 commented on src/partials/about-modal.html
> +    <svg class="team__modal-icon" width="30" height="30" viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg">
done

2021-11-10 08:58 UTC, Vitaliy-Karpenko529 commented on src/sass/components/_about.scss
> +@media screen and (min-width: $tablet) {
done

2021-11-10 08:59 UTC, Vitaliy-Karpenko529 commented on src/sass/components/_about.scss
> +.container {
done

2021-11-10 09:05 UTC, Vitaliy-Karpenko529 commented on src/js/about.js
> +import refs from "./common/refs";
done

2021-11-10 09:40 UTC, vtyshchenko approved these changes

2021-11-10 10:57 UTC, ViktoriiaPavlenko approved these changes

2021-11-10 11:50 UTC, merged