Feature/spinner
vtyshchenko/project-filmoteka pull request #24
Opened 2021-11-10 19:41 UTC by Vitaliy-Karpenko529

2021-11-10 21:18 UTC, emmavasylyk approved these changes

2021-11-10 21:57 UTC, vtyshchenko requested changes

2021-11-10 21:57 UTC, vtyshchenko commented on src/sass/utils/_variables.scss
> +$color1: red;
назви кольори так,щоб було відомо, що це відноситься до спінера
назв кольорів не повинно бути - тільки хексом

2021-11-10 21:57 UTC, vtyshchenko commented on src/sass/utils/_variables.scss
> +$mask-kolor: rgba(233, 167, 134, 0.75);
color - помилка в слові

2021-11-11 10:11 UTC, Vitaliy-Karpenko529 commented on src/sass/utils/_variables.scss
> +$color1: red;
done

2021-11-11 10:11 UTC, Vitaliy-Karpenko529 commented on src/sass/utils/_variables.scss
> +$mask-kolor: rgba(233, 167, 134, 0.75);
done

2021-11-11 12:54 UTC, vtyshchenko approved these changes

2021-11-11 12:54 UTC, merged