Feature/search genres
vtyshchenko/project-filmoteka pull request #30
Opened 2021-11-11 13:19 UTC by marynaost

2021-11-11 15:19 UTC, ViktoriiaPavlenko approved these changes

2021-11-11 16:05 UTC, vtyshchenko requested changes

2021-11-11 16:05 UTC, vtyshchenko commented on src/js/searchGenresAndYear.js
> +
потрібна перевірка на те, що genres не null

2021-11-11 16:05 UTC, vtyshchenko commented on src/js/searchGenresAndYear.js
> +        item.genre_ids = genresArr
мутація вхідних даних - погана ідея
const newData = data.results.map(...)

return newData;

2021-11-11 16:05 UTC, vtyshchenko commented on src/js/searchGenresAndYear.js
> +        genres.find(genr => {
для чого тут find? Він знаходить і повертає по певній умові - ти нікому нічого не просаоюєш і умови пошуку немає куди повернути результат

2021-11-11 16:05 UTC, vtyshchenko commented on src/js/searchGenresAndYear.js
> +    data.results.map(item => {
msp не змінює масив, алише повертає новий зі змінами

2021-11-11 16:05 UTC, vtyshchenko commented on src/js/searchGenresAndYear.js
> +  data.results.map(elem => {
мутація вхідних даних - погана ідея
const newData = data.results.map(...)
return newData;

2021-11-12 12:32 UTC, vtyshchenko approved these changes

2021-11-12 12:32 UTC, merged