Feature/pagination
vtyshchenko/project-filmoteka pull request #42
Opened 2021-11-13 00:56 UTC by barometer-js

2021-11-13 11:28 UTC, vtyshchenko requested changes
мобілка також є чи тільки десктоп та планшет.
Бо я мобілки не бачу
Видали коментарі кирилицею

2021-11-13 11:28 UTC, vtyshchenko commented on src/js/common/refs.js
> +  wrapper: document.querySelector('.pagination__wrapper-js'),
wrapper та listernerEvent - дубляжі ( 28 та 31 строчка)

в js коді також виправ

2021-11-13 11:28 UTC, vtyshchenko commented on src/js/pagination.js
> +const { wrapper, arrowLeft, arrowRight, listernerEvent } = refs.refs;
убери дубляжі з рефів

2021-11-13 11:28 UTC, vtyshchenko commented on src/js/pagination.js
> +  onMarkupButton(totalPages, page);
19, 20  - винеси в функцію з одним параметром page і заміни ці строки на визов цієї функції
26,27 та 53,54 - аміни ці строки також на визов цієї функції

2021-11-14 15:27 UTC, barometer-js commented on src/js/common/refs.js
> +  wrapper: document.querySelector('.pagination__wrapper-js'),
Виправив

2021-11-14 15:28 UTC, barometer-js commented on src/js/pagination.js
> +const { wrapper, arrowLeft, arrowRight, listernerEvent } = refs.refs;
Виправив

2021-11-14 15:40 UTC, barometer-js commented on src/js/pagination.js
> +  onMarkupButton(totalPages, page);
Ці функції очікують два параметри. Нажаль не можу змінити.

2021-11-14 21:14 UTC, vtyshchenko approved these changes

2021-11-14 21:29 UTC, vtyshchenko approved these changes

2021-11-15 15:46 UTC, emmavasylyk approved these changes

2021-11-15 15:48 UTC, ViktoriiaPavlenko approved these changes

2021-11-15 15:50 UTC, merged