added total pages to local storage
vtyshchenko/project-filmoteka pull request #49
Opened 2021-11-13 19:51 UTC by ViktoriiaPavlenko

2021-11-13 19:57 UTC, marynaost approved these changes

2021-11-13 22:57 UTC, vtyshchenko requested changes

2021-11-13 22:57 UTC, vtyshchenko commented on src/js/watched-queue-btns.js
> +    localStorage.setItem('pageType', 'watched');
винеси в окрему функцію з параметрами і заміни  25, 41 та 46 строчку

2021-11-13 22:57 UTC, vtyshchenko commented on src/js/watched-queue-btns.js
> +        totalPages = Math.floor(data.watched.length / 20) + 1
винеси в окрему функцію з параметрами і заміни 20 та 23 строчку

2021-11-14 07:40 UTC, vtyshchenko approved these changes

2021-11-14 07:40 UTC, merged