Feature page header
vtyshchenko/project-filmoteka pull request #5
Opened 2021-11-07 10:11 UTC by Dima-as

2021-11-07 10:56 UTC, vtyshchenko requested changes

2021-11-07 10:56 UTC, vtyshchenko commented on src/partials/header.html
> +      <a href="" class="link logo">
<a href="#" class="link logo">

2021-11-07 10:56 UTC, vtyshchenko commented on src/partials/header.html
> +    <div class=" wrapper">
wrapper переіменуйте на header__wrapper

2021-11-07 10:56 UTC, vtyshchenko commented on src/partials/header.html
> +        <button class="btn-watched" id="btn-watched">
додайте type="button"

2021-11-07 10:56 UTC, vtyshchenko commented on src/partials/header.html
> +        <button class="btn-queue" id="btn-queue">
додайте type="button"

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +    @media screen and (min-width: 768px) {
використовуйте змінні 
$mobile-min: 320px;
$mobile: 480px;
$tablet: 768px;
$desktop: 1024px;

замініть всюди

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +      @media screen and (min-width: 1024px) {
використовуйте змінні 
$mobile-min: 320px;
$mobile: 480px;
$tablet: 768px;
$desktop: 1024px;

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +    @media screen and (max-width: 767px) {
це правило не потрібне. Просто перенесіть width: 280px без правила

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +  font-family: 'Roboto', sans-serif;
використовуйте змінніз 
sass/_variables.scss

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +  color: #ffffff;
всі кольолри також беріть з 
sass/_variables.scss

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +        rgba(0, 0, 0, 0.56),
всі кольолри беріть з змінних в
sass/_variables.scss

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +        rgba(0, 0, 0, 0.56),
всі кольолри беріть з змінних в
sass/_variables.scss

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +            rgba(0, 0, 0, 0.56),
всі кольолри беріть з змінних в
sass/_variables.scss

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +        rgba(0, 0, 0, 0.56),
всі кольолри беріть з змінних в
sass/_variables.scss

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +        rgba(0, 0, 0, 0.56),
всі кольолри беріть з змінних в
sass/_variables.scss

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +            rgba(0, 0, 0, 0.56),
всі кольолри беріть з змінних в
sass/_variables.scss

далі самі перевірте кольори

2021-11-07 10:56 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +  transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1);
замініть змінними з
sass/_variables.scss
$anim-timing-function
$anim-duration

2021-11-08 07:48 UTC, vtyshchenko requested changes

2021-11-08 07:48 UTC, vtyshchenko commented on src/sass/layout/_header.scss
> +.is-hidden{
по можливості потрібно використовувати .visually-hidden, а не .visually-hidden

2021-11-08 07:48 UTC, vtyshchenko commented on src/js/header.js
> +    const currentHeader = {
чому ви просто не присвоїте значення змінним? Напр.
const home = 'header__home';

2021-11-08 16:55 UTC, vtyshchenko requested changes

2021-11-08 16:55 UTC, vtyshchenko commented on src/js/header.js
> +    // const currentHeader = {
закоментований код видаляйте

2021-11-08 17:11 UTC, vtyshchenko approved these changes

2021-11-08 19:31 UTC, emmavasylyk requested changes

2021-11-08 19:31 UTC, emmavasylyk commented on src/partials/header.html
> +            class="nav__btn" id="btn-library">MY LIBRARY</button>
Весь текст должен быть с маленькой буквы, а стилях указывать что буквы большие(text-transform: uppercase), кроме заглавных. Пересмотри если что весь хедер.

2021-11-08 19:31 UTC, emmavasylyk commented on src/partials/header.html
> +      <Input class="header-form__input" type="text" name="query"
Input поменять на input

2021-11-08 19:46 UTC, Dima-as commented
Не совсем понял по поводу второго замечания?

пн, 8 нояб. 2021 г., 21:31 emmavasylyk ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/partials/header.html
> <https://github.com/vtyshchenko/project-filmoteka/pull/5#discussion_r745029909>
> :
>
> > +<header class="header header__home">
>
> +  <div class="container">
>
> +    <div class=" header__wrapper">
>
> +      <a href="#" class="link logo">
>
> +        <span class="logo__icon"></span>
>
> +        <span class="logo__label">Filmoteka</span>
>
> +      </a>
>
> +      <nav class="nav">
>
> +        <ul class="list nav__list">
>
> +          <li class="nav__item js-home">
>
> +            <button type="button"
>
> +            class="nav__btn current" id="btn-home">Home</button>
>
> +          </li>
>
> +          <li class="nav__item js-lib">
>
> +            <button type="button"
>
> +            class="nav__btn" id="btn-library">MY LIBRARY</button>
>
>
> Весь текст должен быть с маленькой буквы, а стилях указывать что буквы
> большие(text-transform: uppercase), кроме заглавных. Пересмотри если что
> весь хедер.
> ------------------------------
>
> In src/partials/header.html
> <https://github.com/vtyshchenko/project-filmoteka/pull/5#discussion_r745030671>
> :
>
> > +      </a>
>
> +      <nav class="nav">
>
> +        <ul class="list nav__list">
>
> +          <li class="nav__item js-home">
>
> +            <button type="button"
>
> +            class="nav__btn current" id="btn-home">Home</button>
>
> +          </li>
>
> +          <li class="nav__item js-lib">
>
> +            <button type="button"
>
> +            class="nav__btn" id="btn-library">MY LIBRARY</button>
>
> +          </li>
>
> +        </ul>
>
> +      </nav>
>
> +    </div>
>
> +    <form action="" class="header-form">
>
> +      <Input class="header-form__input" type="text" name="query"
>
>
> Input поменять на input
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vtyshchenko/project-filmoteka/pull/5#pullrequestreview-800524809>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATF5UD6IZP4KF5KRTBTAYVDULAQSHANCNFSM5HQUQ5PQ>
> .
>

2021-11-08 20:36 UTC, emmavasylyk approved these changes

2021-11-08 20:37 UTC, merged