Bag fix/team mobile
vtyshchenko/project-filmoteka pull request #52
Opened 2021-11-13 20:10 UTC by Vitaliy-Karpenko529

2021-11-13 20:30 UTC, ViktoriiaPavlenko approved these changes

2021-11-13 22:52 UTC, vtyshchenko requested changes

2021-11-13 22:52 UTC, vtyshchenko commented on src/sass/components/_about.scss
убери всі дублікати класів. Клас повинен бути тільки в одному місці

2021-11-14 06:44 UTC, Vitaliy-Karpenko529 commented on src/sass/components/_about.scss
Done

2021-11-14 07:14 UTC, ViktoriiaPavlenko approved these changes

2021-11-14 07:41 UTC, vtyshchenko approved these changes

2021-11-14 07:42 UTC, merged

2021-11-14 07:42 UTC, emmavasylyk approved these changes