Feature/up button
vtyshchenko/project-filmoteka pull request #64
Opened 2021-11-14 20:52 UTC by dimperesichan

2021-11-14 21:26 UTC, vtyshchenko requested changes

2021-11-14 21:26 UTC, vtyshchenko commented on src/index.js
> +import './js/watchedQueueBtns'
видали цю строчку. Такого файлу вже немає

2021-11-14 21:26 UTC, vtyshchenko commented on src/sass/components/_up-button.scss
> +    background: #f5f5f5;
всі кольори тільки з _variables.scss
Якщо там немає - занеси туди з своєю назвою (щоб не дублювалася)

2021-11-14 21:26 UTC, vtyshchenko commented on src/sass/components/_up-button.scss
> +        // background-color: $title-color;
коментарі видали

2021-11-15 19:44 UTC, vtyshchenko approved these changes

2021-11-15 19:59 UTC, ViktoriiaPavlenko approved these changes

2021-11-15 20:00 UTC, merged