Feature/go to pages
vtyshchenko/project-filmoteka pull request #79
Opened 2021-11-17 20:38 UTC by barometer-js

2021-11-17 22:10 UTC, vtyshchenko requested changes

2021-11-17 22:10 UTC, vtyshchenko commented on src/js/api-service.js
> +  const LANG = localStorage.getItem('language');
localStorage.getItem('language') - для цього є функція в getLanguage() в src/js/common/api-data.js

заміни всюди

2021-11-17 22:10 UTC, vtyshchenko commented on src/js/common/refs.js
> +  modalTrailerWindowRefs: document.querySelector('.modal-trailer'),
є дубляжі - убери

2021-11-17 22:10 UTC, vtyshchenko commented on src/js/pagination.js
> +  return localStorage.getItem('totalPages');
перевірка на null є?
Якщо немає такого ключа в localStorage?

2021-11-17 22:10 UTC, vtyshchenko commented on src/js/pagination.js
> +  const pageType = localStorage.getItem('pageType');
перевірка на nill чи  undefined

2021-11-17 22:10 UTC, vtyshchenko commented on src/js/search-by-keyword.js
> +      console.log('Vika totalPages');
видали

2021-11-17 22:27 UTC, barometer-js commented on src/js/api-service.js
> +  const LANG = localStorage.getItem('language');
замінив на getLanguage() та підключив імпорт функції

2021-11-17 22:31 UTC, barometer-js commented on src/js/common/refs.js
> +  modalTrailerWindowRefs: document.querySelector('.modal-trailer'),
Видалив:
modalTrailerWindowRefs: document.querySelector('.modal-trailer'),
  modalTrailerContainerRefs: document.querySelector('.modal-trailer-container'),

2021-11-18 00:10 UTC, barometer-js commented on src/js/pagination.js
> +  return localStorage.getItem('totalPages');
Додав перевірку

2021-11-18 00:17 UTC, barometer-js commented on src/js/pagination.js
> +  const pageType = localStorage.getItem('pageType');
Додав перевірку

2021-11-18 00:19 UTC, barometer-js commented on src/js/search-by-keyword.js
> +      console.log('Vika totalPages');
Видалив

2021-11-18 13:24 UTC, vtyshchenko requested changes

2021-11-18 13:24 UTC, vtyshchenko commented on src/js/pagination.js
> +    return (totalPages = 1);
return (totalPages = 1);

правильно

    return 1;

2021-11-18 13:24 UTC, vtyshchenko commented on src/js/pagination.js
> +    return (pageType = 1);
pageType не можк бути числом

pageType = 'popular';

2021-11-18 13:42 UTC, marynaost approved these changes

2021-11-18 14:57 UTC, Dima-as approved these changes

2021-11-18 17:23 UTC, barometer-js commented on src/js/pagination.js
> +    return (totalPages = 1);
Виправив

2021-11-18 17:23 UTC, barometer-js commented on src/js/pagination.js
> +    return (pageType = 1);
Виправив

2021-11-18 17:52 UTC, ViktoriiaPavlenko approved these changes

2021-11-18 18:36 UTC, vtyshchenko approved these changes

2021-11-18 18:36 UTC, merged